services:
- type: web
  name: web
  env: elixir
  repo: https://github.com/zestcreative/petal.git
  branch: render
  buildCommand: ./build.sh
  startCommand: _build/prod/rel/petal/bin/petal start
  envVars:
  - key: ELIXIR_VERSION
    value: 1.11.3
  - key: ERLANG_VERSION
    value: 23.2.4
  - key: SECRET_KEY_BASE
    sync: false
  - key: DATABASE_URL
    fromDatabase:
      name: db
      property: connectionString
  autoDeploy: false             # optional

databases:
- name: db
  ipAllowList: []
